### ISSUE TITLE
Compiling error

### ISSUE THREAD

**Issue by Tkastylevsky** [jydu/coalhmm#1]
Hello ! 
I've been trying to install coalhmm to try to estimate ILS in my sequences, after reading the paper that came out earlier this year on marsupials, but I keep getting compilation errors. I've tried to install Bpp-core, seq and phyl through conda, (they're at the 2.4.1 version there), and then compiling coalhmm, but It didn't work. I can run the Cmake line (cmake -DCMAKE_INSTALL_PREFIX=$HOME/.local) but the make encounters an error (
/home/admintimothee/.local/include/Bpp/Numeric/Parameter.h:142:5: note:   candidate expects 0 arguments, 3 provided
make[2]: *** [CoalHMM/CMakeFiles/libcoalhmm-shared.dir/build.make:63 : CoalHMM/CMakeFiles/libcoalhmm-shared.dir/ThreeSpeciesCoalHmmStateAlphabet07.cpp.o] Erreur 1
make[1]: *** [CMakeFiles/Makefile2:221 : CoalHMM/CMakeFiles/libcoalhmm-shared.dir/all] Erreur 2
make: *** [Makefile:152 : all] Erreur 2)
I then compiled Bpp from source, both the 2.3 version (as stated on your Readme), but the coalhmm cmake told me that I needed a newer version. I then tried it with the 2.4 version, compiled from source, but I encountered the same error as with the conda packages. 
Would you have any pointers for me ? 
many thanks,

**Comment by jydu** [comment]
Hi,

Since the Bio++ libraries are ongoing a major update, the CoalHMM code is currently not in sync. Before I fix this, did you try the statistically linked executable provided in the 'release' section? Could it work for you by any chance?

Julien.

**Comment by Tkastylevsky** [comment]
Hi, 
the executable can be run on the example, great ! Is there a specific resource that could help me understand all the different parameters of the param file, as well as the various files that I get as outputs ? 
Timothee

**Comment by jydu** [comment]
Hi Timothee,

Great that the exe works. As for the documentation, there is not much as the program has never been officially released (and time passes by...). But, basically, there are two example option files, one for the two species divergence model, and one for the ILS model that are provided with annotations. Option names should be relatively explicit. For instance, output.userfriendly.parameters will provide all estimated parameters, while output.posterior.values will store the posterior decoding. Do not hesitate to get in touch if you need more explanations.

Best,

Julien.

**Comment by bettermaan** [comment]
Hi Julien,

After running ILS.bpp in the Example, I am confused about the result that I got.  I know there are 4 hidden states in total, HC1, HC2, HG and CG, but the result file (output.posterior.values and output.posterior.segments) does not specify which state correspond to HC1, HC2, HG and CG. 

Best,
Huijie

**Comment by jydu** [comment]
Hi Huijie,

They are exactly in that order! State 0 is HC1, 1 is HC2, 2 is HG and 3 is CG (columns V0, V1, V2 and V3).
Hope this helps,

Julien.

**Comment by bettermaan** [comment]
Hi Julien,

Thanks for your very useful help.

Recently I ran coalhmm on my own data,  and it goes well. But I still had some confusions about the coalhmm.
1)  if there is introgression between species1 and species 2 or species 3, how will it affect the result?
2)  I noticed that some sites have not much difference between v2 and v3,for example, V0: 0.0953065,V1: 0.233771,V2: 0.290776,V3: 0.380147. Although V3 is the largest, the difference is relatively small, does this result reliable?
3)  Just to be sure, I set species1 as a, species2 as b, and species3 as c in ILS.bpp, then in the result state0 is ab1, 1 is ab2, 2 is ac, 3 is bc  (columns V0, V1, V2 and V3).

Best,
Huijie

**Comment by jydu** [comment]
Hi Huijie,

Point 1 is a good point. We did not investigate the effect of introgression between sp1 and sp2 as it would not impact the underlying topology. My expectation there would be that introgression would then lead to an underestimation of the speciation time (parameter tau1) and an overestimation of the ancestral Ne (parameter theta1). Introgression between sp1 (or sp2) and sp3 has more predictable results, as it will lead the ILS topologies to be in non-equal frequencies. Such a difference in frequency, however, cannot be taken as evidence for introgression, as other reasons could cause this, such as ancestral pop structure or different mutation rates in the terminal branches of the species tree.

Point 2: as you go away from parsimony informative sites, the topology support will mechanically drop. As a matter of facts, many sites will show low support for a particular scenario. You can implement several types of filtering, for instance based on entropy, and see their effects on the results of your analyses. Support for the alternative genealogies will tend to be lower than for the species tree.

Point 3: that is correct: 0:(a,b),c 1:(a,b),c with longer branches for a and b, 2:(a,c),b and 3: (b,c),a

All the best,

Julien.
