### ISSUE TITLE
install erroe

### ISSUE THREAD

**Issue by gaoming-liu** [jydu/coalhmm#2]
Hello,
I want to used coalhmm to estimate ILS for the sequence, but report the following error. I used the bio++ version 2.4.1  and 2.3.0 on the ubuntu system. The errors is the same. 
 
/coalhmm/CoalHMM/CoalHmmEmissionProbabilities.cpp:43:56: error: invalid conversion from 'bpp::AlignedValuesContainer*' to 'bpp::SiteContainer*' [-fpermissive]
   SiteContainer* zipSites = PatternTools::shrinkSiteSet(data);
                             ~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~
/media/science/liugm/liugm/software/coalhmm/CoalHMM/CoalHmmEmissionProbabilities.cpp:43:61: error: cannot convert from pointer to base class 'bpp::AlignedValuesContainer' to pointer to derived class 'bpp::SiteContainer' because the base is virtual
   SiteContainer* zipSites = PatternTools::shrinkSiteSet(data);
                                                             ^
/media/science/liugm/liugm/software/coalhmm/CoalHMM/CoalHmmEmissionProbabilities.cpp:54:22: error: 'areSitesIdentical' is not a member of 'bpp::SiteTools'
       if (SiteTools::areSitesIdentical(zipSites->getSite(ii), *site1))

Would you fix that error or give me some guide to install that software.
thanks.

**Comment by jydu** [comment]
Hi,

The Bio++ libraries are currently undergoing a major update and CoalHMM is temporarily out of sync. Did you try the static executable available in the "release" section of the github repository?

Best,

Julien.
