### ISSUE TITLE
parameter of ILS.bpp

### ISSUE THREAD

**Issue by gyq-123** [jydu/coalhmm#4]
Hi
    I running coalhmm according to the default parameter of ILS.bpp in the example file, but I am confused about the following parameters. I do not know how to adjust the Settings.
tau1=0.004,
tau2=0.0015,
c2=0.010,
theta1=0.002,
theta2=0.002,

**Comment by jydu** [comment]
Hi,

I am sincerely sorry, only seeing this now... These are initial values for the parameters, they will be estimated. You can leave them as is!

Julien.
